### ISSUE TITLE
Choose framework

### ISSUE THREAD

**Issue by Space647** [memory-cards/cards-exporter#4]
As a framework, I suggest choosing Koa or Express. 
Links:
https://expressjs.com/
https://koajs.com/

**Comment by StolpnerA** [comment]
@vvscode you said that `Next` work with `express` much good, am I wrong?

**Comment by vvscode** [comment]
@StolpnerA, in fact, it also works with koa https://medium.com/ninjadevs/node-7-6-koa-2-asynchronous-flow-control-made-right-b0d41c6ba570

For production, I would prefer express - much more modules and so on. 

In this project - I'm ok about both. Or even about pure node.js code

**Comment by vvscode** [comment]
https://github.com/koajs/koa/blob/master/docs/koa-vs-express.md

**Comment by vvscode** [comment]
@Space647 @StolpnerA @zenby  any updates/thoughts?

**Comment by zenby** [comment]
As for me I would leave `express` because I don't find any pros of using `koa` here. Moreover `expess` satisfies all our needs and I don't think that we should concentrate on it.

**Comment by vvscode** [comment]
Guys. This issue is almost a  blocker for the rest of the work.

Let's vote till Sunday morning - for this comment - thumb up - keep as is, thumb down - change choice ( and give your proposal )

**Comment by vvscode** [comment]
I'm personally ready to try https://nestjs.com/
